# Revisão de Álgebra Linear

Como explicado anteriormente, vamos utilizar a biblioteca numpy para manipulação de vetores e matrizes. Ambos são definidos como arrays, de uma ou duas dimensões, respectivamente.

In [19]:
import numpy as np

# vetor
v = np.array([1,2,3]) # alternativa: np.arange(1,4)
print(v)

# matriz
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)

# matriz como lista de vetores (por linha) 
V3 = np.array([v,v,v])
print(V3)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
# vetor nulo
z = np.zeros(3)
print(z)

# matriz nula
Z = np.zeros((3,2))
print(Z)

# vetor de uns
e = np.ones(4)
print(e)

[ 0.  0.  0.]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[ 1.  1.  1.  1.]


In [17]:
# matriz diagonal
D = np.diag(range(1,5))
print(D)

# matriz identidade
I = np.diag(np.ones(4))
print(I)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


O que faz a função abaixo?

In [21]:
L = np.tril(M)
print(L)

[[1 0 0]
 [1 2 0]
 [1 2 3]]


O que faz a função abaixo?

In [24]:
print(M)
print(L)
print(M * L)

(array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]]), array([[ 1,  0,  0],
       [ 4, 10,  0],
       [ 7, 16, 27]]))


In [29]:
print(np.matmul(M,L))
print(np.dot(M,np.arange(3)))


[[ 6 10  9]
 [15 22 18]
 [24 34 27]]
[ 8 17 26]


## Produto Interno e Externo

 * Interno: Calculado através da função np.dot.
 * Externo: Calculado através da função np.outer.

In [34]:
np.dot(v,v)

14

In [35]:
np.outer(v,v)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

## Posto de uma matriz

O posto de uma matriz $A_{m\times n}$ é o máximo entre o número de vetores linha linearmente independentes e o número de colunas linearmente independentes. 

In [36]:
np.linalg.matrix_rank(M)

2