# Revisão de Álgebra Linear

Como explicado anteriormente, vamos utilizar a biblioteca numpy para manipulação de vetores e matrizes. Ambos são definidos como arrays, de uma ou duas dimensões, respectivamente.

In [1]:
import numpy as np

# vetor
v = np.array([1,2,3]) # alternativa: np.arange(1,4)
print(v)

# matriz
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)

# matriz como lista de vetores (por linha) 
V3 = np.array([v,v,v])
print(V3)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [2]:
# vetor nulo
z = np.zeros(3)
print(z)

# matriz nula
Z = np.zeros((3,2))
print(Z)

# vetor de uns
e = np.ones(4)
print(e)

[ 0.  0.  0.]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[ 1.  1.  1.  1.]


In [3]:
# matriz diagonal
D = np.diag(range(1,5))
print(D)

# matriz identidade
I = np.diag(np.ones(4))
print(I)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


O que faz a função abaixo?

In [4]:
L = np.tril(M)
print(L)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


## Produtos de Matrizes
<img src="images/shop.png" alt="floating point" style="width: 100%"/>(Source: [Several Simple Real-world Applications of Linear Algebra Tools](https://www.mff.cuni.cz/veda/konference/wds/proc/pdf06/WDS06_106_m8_Ulrychova.pdf))

A função abaixo *não* calcula o produto de matrizes. Ela faz o produto elemento-a-elemento.

In [17]:
print(M)
print(L)
print(M * L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[ 1  0  0]
 [16 25  0]
 [49 64 81]]


A função matmul deve ser usada para calcular o produto de matrizes.

In [68]:
print(np.matmul(M,L))
print(M.dot(L))
print(np.dot(M,np.arange(3)))


[[ 30  34  27]
 [ 66  73  54]
 [102 112  81]]
[[ 30  34  27]
 [ 66  73  54]
 [102 112  81]]
[ 8 17 26]


## Produto Interno e Externo

 * Interno: Calculado através da função np.dot.
 * Externo: Calculado através da função np.outer.

In [72]:
v = np.arange(1,4)
u = np.arange(4,7)
print(u,v,np.dot(u,v))

(array([4, 5, 6]), array([1, 2, 3]), 32)


In [75]:
M = np.outer(v,v)
print(M)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


## Posto de uma matriz

O posto de uma matriz $A_{m\times n}$ é o máximo entre o número de vetores linha linearmente independentes e o número de colunas linearmente independentes. 

In [76]:
np.linalg.matrix_rank(M)

1

## Outras funções importantes

Criando uma matriz aleatória.

In [77]:
A = np.random.rand(3,2)
print(A)

[[ 0.01614433  0.77920084]
 [ 0.529526    0.26897115]
 [ 0.04034866  0.03500766]]


Matriz transposta.

In [78]:
A.transpose()

array([[ 0.01614433,  0.529526  ,  0.04034866],
       [ 0.77920084,  0.26897115,  0.03500766]])

Gerando uma matriz simétrica e verificando a simetria.

In [79]:
A = np.random.rand(3,3)
A = (A + A.transpose())/2
print(A)

[[ 0.3490637   0.30482848  0.49346712]
 [ 0.30482848  0.61675409  0.1734747 ]
 [ 0.49346712  0.1734747   0.77924667]]


In [80]:
print(A==A.transpose())
print(np.all(A==A.transpose()))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
True


Determinante.
Definido apenas para matrizes quadradas. Pode ser calculado pela regra de Laplace:

$$
\det(A) = (-1)^{1+1} a_{11}\det(A_{11}) + (-1)^{1+2}a_{12}\det(A_{12}) + \ldots +
(-1)^{1+j}a_{1j}\det(A_{1j}) + \ldots (-1)^{1+n}a_{1n}\det(A_{1n})
$$

In [23]:
np.linalg.det(A)

0.15946459125216983

In [25]:
np.trace(A)

0.43665179012235011

In [85]:
invA = np.linalg.inv(A)
np.allclose(A.dot(invA),np.eye(3))

True

## Propriedades da inversa e da transposta

 * $(A^\top)^\top = A$ e $(A^{-1})^{-1} = A$
 * $(A^{-1})^\top = (A^\top)^{-1}$
 * Se $A = BCD$, então $A^\top = D^\top C^\top B^\top$ e $A^{-1} = D^{-1} C^{-1} B^{-1}$
 * $(A^\top + B^\top) = (A+B)^\top$, mas $(A^{-1} + B^{-1}) \neq (A+B)^{-1}$

## Autovalores e autovetores

Relação de uma matriz $A$ de ordem $n$ com seus autovalores $\lambda$ e seus respectivos autovetores $v$:

$$
Av = \lambda v
$$

In [86]:
# Exemplo
A = np.array([[10,-4], [12, -4]])
v = np.array([1,2])

print(np.dot(A,v))

[2 4]


In [32]:
autovals, autovecs = np.linalg.eig(A)
print(autovals)
print(autovecs)

[ 4.  2.]
[[ 0.5547002   0.4472136 ]
 [ 0.83205029  0.89442719]]


Falar de polinômio característico no quadro. Pular normas vetoriais e normais matriciais por enquanto.

## Solução de Sistemas Lineares

Sistema triangular inferior: método das substituições sucessivas.

In [87]:
A = np.tril(np.random.rand(3,3))
b = np.random.rand(3)
print(A)
print(b)

[[ 0.22836111  0.          0.        ]
 [ 0.51212116  0.83891964  0.        ]
 [ 0.60966786  0.94001156  0.04660697]]
[ 0.76734159  0.50334633  0.78582493]


In [88]:
def substituicoesSucessivas(L,c):
    n = len(c)
    assert(L.shape == (n,n))
    
    x = np.zeros(n)
    for i in range(n): #for(i=0; i<n; i++)
        soma = 0.0
        for j in range(i):
            soma += L[i,j]*x[j]
        x[i] = (c[i]-soma)/L[i,i] 
        
    return x

In [90]:
x = substituicoesSucessivas(A,b)
print(x)

[ 3.36021126 -1.45125813  2.1758882 ]


In [91]:
np.dot(A,x)

array([ 0.76734159,  0.50334633,  0.78582493])

Sistema triangular superior: substituições retroativas (mesma ideia).

Qual a ordem do número de operações?

In [92]:
def substituicoesRetroativas(U,d):
    n = len(d)
    assert(U.shape == (n,n))
    
    x = np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i] = d[i]
        for j in range(i+1,n):
            x[i] -= x[j]*U[i,j]
            
        x[i] /= U[i,i]
        
    return x

In [94]:
U = np.triu(np.random.rand(3,3))
d = np.random.rand(3)
print(U)
print(d)
x = substituicoesRetroativas(U,d)
print(np.allclose(U.dot(x),d))

[[ 0.86700549  0.58877923  0.1823046 ]
 [ 0.          0.53845327  0.50952528]
 [ 0.          0.          0.50504054]]
[ 0.50984577  0.30749178  0.49544158]
True


## Eliminação de Gauss e sistemas equivalentes

Dois sistemas de equações lineares são ditos equivalentes se possuem o mesmo vetor solução.

<b>Ideia da eliminação de Gauss</b>: uma sequência de transformações de $Ax = b$ em sistemas equivalentes que torna a matriz $A$ em uma matriz triangular superior.

As transformações que geram sistemas equivalentes são conhecidas como operações elementares. São elas:
 * multiplicar uma linha (ou coluna) por uma constante não-nula
 * multiplicar uma linha (ou coluna) por uma constante não-nula e somar à outra
 * trocar duas linhas (ou duas colunas de posição
 
Q: Suponha que $A$ é uma matriz quadrada. Quais das operações alteram o determinante de $A$?

In [51]:
def eliminacaoDeGauss(A, b):
    n = len(b)
    assert(A.shape == (n,n))
    
    for j in range(n-1):
        for i in range(???):
            m = ???
            for k in range(???):
                A[i,k] -= ???
            b[i] -= ???
    return A, b

In [54]:
A = np.array([[1,-3,2],[-2,8,-1],[4,-6,5]])
b = np.array([11,-15,29])
U,d = eliminacaoDeGauss(A,b)
print(U)
print(d)

[[  1  -3   2]
 [  0   2   3]
 [  0   0 -12]]
[ 11   7 -36]


In [57]:
x = substituicoesSucessivas(U,d)
print(x)
r = b-np.dot(A,x)
print(r)

[ 11.    3.5   3. ]
[ 4.5 -9.   0. ]


Note que a eliminação de Gauss só executa um tipo de operação elementar. Este tipo <b>não</b> altera o determinante da matriz resultante. Seja $U$ a matriz retornada ao se aplicar a eliminação de Gauss à matriz $A$. Temos que

$$
\det(A) = \prod_{i=1}^n U_{ii}.
$$